# Generated by Django 4.0 on 2022-08-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0021_aiservice_breed_aiservice_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='clinicalservice',
            name='history',
        ),
        migrations.RemoveField(
            model_name='clinicalservice',
            name='number_of_animals',
        ),
        migrations.RemoveField(
            model_name='clinicalservice',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='clinicalservice',
            name='species',
        ),
    ]
