# Generated by Django 4.0 on 2022-08-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lab_exam', '0002_labexam_paid_labtechnique_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='labexam',
            name='case_holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
