# Generated by Django 4.0 on 2022-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_vaccinestock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalequipment',
            name='unit',
            field=models.CharField(default='PCS', max_length=100),
        ),
    ]
