# Generated by Django 4.0 on 2022-07-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='vaccine_id',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_id',
            field=models.ManyToManyField(to='vaccination.Vaccine'),
        ),
    ]
