# Generated by Django 4.0 on 2022-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_vaccination_breed_vaccination_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
