# Generated by Django 4.0 on 2022-10-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0019_alter_customer_mobile_number'),
        ('vaccination', '0007_vaccination_paid_vaccination_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='dx',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='species',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='species',
            field=models.ManyToManyField(to='registernewuser.Species'),
        ),
    ]
