# Generated by Django 4.0 on 2022-07-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0014_prescription_delivered'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalequipment',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regulartreatedanimals.unit'),
        ),
    ]
