# Generated by Django 4.0 on 2022-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_clinicalequipment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestock',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
