# Generated by Django 4.0 on 2022-07-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registernewuser', '0012_remove_customer_treatment_history'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vaccination', '0002_remove_vaccination_vaccine_id_vaccination_vaccine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('HP', 'Health Post'), ('ZR', 'Zone Reverse'), ('Emergency', 'Emergency'), ('Expired', 'Expired Drugs'), ('General', 'General Sale')], max_length=50)),
                ('store_man', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('batch_number', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_approved_by', to='auth.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registernewuser.kebele')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccination.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Regular', 'Regular Fund'), ('Revolving', 'Revolving Fund'), ('Zone', 'Zone Support'), ('Regional', 'Regional Support'), ('NGO', 'Non-Govermental'), ('Other', 'Other')], max_length=50)),
                ('dropped_by', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('batch_number', models.CharField(max_length=100)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('expiration_data', models.DateField()),
                ('remark', models.CharField(max_length=200, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_receiver', to='auth.user')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccination.vaccine')),
            ],
        ),
    ]
