# Generated by Django 4.0 on 2022-07-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vaccine_in_out', '0002_drogoutcashdeposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrogOutCashDeposit',
            new_name='VaccineOutCashDeposit',
        ),
    ]
