# Generated by Django 4.0 on 2022-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_in_out', '0003_rename_drogoutcashdeposit_vaccineoutcashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinein',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vaccineout',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
