# Generated by Django 4.0 on 2022-08-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_in_out', '0005_rename_date_received_vaccinein_date_vaccineout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineout',
            name='unit_price',
        ),
    ]
