# Generated by Django 4.0 on 2022-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_in_out', '0006_remove_vaccineout_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccineout',
            old_name='receiver',
            new_name='kebele',
        ),
        migrations.AddField(
            model_name='vaccineout',
            name='received_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
