# Generated by Django 4.0 on 2023-06-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_in_out', '0007_rename_receiver_vaccineout_kebele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineoutcashdeposit',
            name='payment_for',
        ),
    ]
