# Generated by Django 4.0 on 2022-06-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registernewuser', '0009_alter_customer_case_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('regulartreatedanimals', '0007_alter_unit_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_batch_num', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('dx', models.CharField(max_length=200)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registernewuser.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulartreatedanimals.unit')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registernewuser.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('Internal', 'Internal Parasite'), ('External', 'External Parasite')], max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('dx', models.CharField(max_length=200)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('case_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registernewuser.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulartreatedanimals.unit')),
            ],
        ),
    ]
