# Generated by Django 4.0 on 2022-06-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parasitetreatment',
            options={'verbose_name': 'Parasite Treatment'},
        ),
        migrations.RemoveField(
            model_name='parasitetreatment',
            name='unit',
        ),
    ]
