# Generated by Django 4.0 on 2022-06-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0002_alter_parasitetreatment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parasitetreatment',
            name='quantity',
        ),
    ]
