# Generated by Django 4.0 on 2022-06-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0005_parasiteprescription_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parasiteprescription',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
