# Generated by Django 4.0 on 2022-06-27 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0006_alter_parasiteprescription_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasiteprescription',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
