# Generated by Django 4.0 on 2022-06-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0013_remove_treatedanimal_dx_treatedanimal_dx'),
        ('parasitetreatment', '0007_parasiteprescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parasitetreatment',
            name='dx',
        ),
        migrations.AddField(
            model_name='parasitetreatment',
            name='dx',
            field=models.ManyToManyField(blank=True, to='regulartreatedanimals.Disease', verbose_name='Dx'),
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='dx',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='dx',
            field=models.ManyToManyField(blank=True, to='regulartreatedanimals.Disease', verbose_name='Dx'),
        ),
    ]
