# Generated by Django 4.0 on 2022-07-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0008_remove_parasitetreatment_dx_parasitetreatment_dx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
