# Generated by Django 4.0 on 2022-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0009_delete_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasiteprescription',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
