# Generated by Django 4.0 on 2022-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0013_parasitetreatment_breed_parasitetreatment_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parasiteprescription',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='parasiteprescription',
            name='paid',
        ),
        migrations.AddField(
            model_name='parasitetreatment',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parasitetreatment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
