# Generated by Django 3.1.3 on 2021-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='treatment_history',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
