# Generated by Django 3.1.3 on 2021-03-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0003_auto_20210328_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='breed_id',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='kebele_id',
            new_name='kebele',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='species_id',
            new_name='specie',
        ),
    ]
