# Generated by Django 3.1.3 on 2021-03-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0004_auto_20210328_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='specie',
            new_name='species',
        ),
    ]
