# Generated by Django 3.1.3 on 2021-03-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0006_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='case_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_of_animals',
            field=models.PositiveIntegerField(),
        ),
    ]
