# Generated by Django 3.1.3 on 2021-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0003_auto_20210417_1616'),
        ('registernewuser', '0007_auto_20210330_0640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
