# Generated by Django 4.0 on 2022-07-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0011_delete_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='treatment_history',
        ),
    ]
