# Generated by Django 4.0 on 2022-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0012_remove_customer_treatment_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='price',
            new_name='dis_price',
        ),
        migrations.AddField(
            model_name='drug',
            name='stock_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
