# Generated by Django 4.0 on 2022-08-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0015_drug_dis_unit_drug_stokc_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='stokc_unit',
            new_name='stock_unit',
        ),
    ]
