# Generated by Django 4.0 on 2022-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0016_rename_stokc_unit_drug_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='history',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
