# Generated by Django 4.0 on 2022-08-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0017_customer_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='history',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='number_of_animals',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='species',
        ),
    ]
