# Generated by Django 4.0 on 2022-07-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registernewuser', '0011_delete_vaccine'),
        ('regulartreatedanimals', '0013_remove_treatedanimal_dx_treatedanimal_dx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_batch_num', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registernewuser.customer')),
                ('dx', models.ManyToManyField(blank=True, to='regulartreatedanimals.Disease', verbose_name='Dx')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulartreatedanimals.unit')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccination.vaccine')),
            ],
        ),
    ]
