# Generated by Django 4.0 on 2022-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_remove_vaccination_vaccine_id_vaccination_vaccine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='price',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dis_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
