# Generated by Django 4.0 on 2022-08-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_remove_vaccine_price_vaccine_dis_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='unit',
        ),
    ]
