# Generated by Django 4.0 on 2022-08-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0019_alter_customer_mobile_number'),
        ('vaccination', '0005_vaccination_case_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registernewuser.breed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='history',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='number_of_animals',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registernewuser.species'),
            preserve_default=False,
        ),
    ]
