# Generated by Django 4.0 on 2022-07-28 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_in_out', '0003_clinicalequipmentin_total_clinicalequipmentout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalequipmentout',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
