# Generated by Django 4.0 on 2022-06-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0004_parasiteprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasiteprescription',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
