# Generated by Django 4.0 on 2022-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0010_parasiteprescription_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parasiteprescription',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
