# Generated by Django 4.0 on 2022-08-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasitetreatment', '0011_alter_parasiteprescription_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parasiteprescription',
            name='unit',
        ),
    ]
