# Generated by Django 4.0 on 2022-08-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('regulartreatedanimals', '0019_remove_treatedanimal_clinical_finding_and_more'),
        ('lab_exam', '0003_labexam_case_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('lab_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_exam.labsample')),
                ('lab_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_exam.labtechnique')),
                ('treated_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulartreatedanimals.treatedanimal')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_result', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('case_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('lab_exam_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_exam.labexamrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='LabExam',
        ),
    ]
