# Generated by Django 4.0 on 2022-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_exam', '0005_labexamrequest_lab_result_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='treatment_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
