# Generated by Django 4.0 on 2022-06-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0008_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='case_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
