# Generated by Django 4.0 on 2022-06-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0009_alter_customer_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
