# Generated by Django 4.0 on 2022-07-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Adminstrator'), ('Cashier', 'Cashier'), ('Vet', 'Veternarian'), ('Pharmacist', 'Pharmacist')], max_length=100),
        ),
    ]
