# Generated by Django 4.0 on 2022-07-28 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_in_out', '0004_vaccinein_total_vaccineout_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinein',
            old_name='date_received',
            new_name='date',
        ),
        migrations.AddField(
            model_name='vaccineout',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
