# Generated by Django 3.1.3 on 2021-03-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0006_drug'),
        ('regulartreatedanimals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreatedAnimals',
            new_name='TreatedAnimal',
        ),
    ]
