# Generated by Django 3.1.3 on 2021-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0006_drug'),
        ('regulartreatedanimals', '0002_auto_20210329_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatedanimal',
            name='rx',
        ),
        migrations.AddField(
            model_name='treatedanimal',
            name='rx',
            field=models.ManyToManyField(to='registernewuser.Drug', verbose_name='RX'),
        ),
    ]
