# Generated by Django 3.1.3 on 2021-04-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0005_auto_20210330_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulartreatedanimals.treatedanimal', verbose_name='Treatment ID'),
        ),
        migrations.AlterField(
            model_name='treatedanimal',
            name='pr',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='treatedanimal',
            name='rr',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='RR'),
        ),
        migrations.AlterField(
            model_name='treatedanimal',
            name='t0',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='T0'),
        ),
    ]
