# Generated by Django 4.0 on 2022-06-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0006_auto_20210408_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
