# Generated by Django 4.0 on 2022-06-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0009_prescription_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
