# Generated by Django 4.0 on 2022-07-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0013_remove_treatedanimal_dx_treatedanimal_dx'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
