# Generated by Django 4.0 on 2022-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0014_prescription_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatedanimal',
            name='pr',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='treatedanimal',
            name='rr',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='RR'),
        ),
        migrations.AlterField(
            model_name='treatedanimal',
            name='t0',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T0'),
        ),
    ]
