# Generated by Django 4.0 on 2022-08-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('regulartreatedanimals', '0017_remove_prescription_unit_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatedanimal',
            name='case_holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
