# Generated by Django 4.0 on 2022-08-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0019_alter_customer_mobile_number'),
        ('regulartreatedanimals', '0018_treatedanimal_case_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatedanimal',
            name='clinical_finding',
        ),
        migrations.RemoveField(
            model_name='treatedanimal',
            name='differential_diag',
        ),
        migrations.RemoveField(
            model_name='treatedanimal',
            name='dx',
        ),
        migrations.RemoveField(
            model_name='treatedanimal',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='treatedanimal',
            name='rr',
        ),
        migrations.RemoveField(
            model_name='treatedanimal',
            name='rumen_motility',
        ),
        migrations.RemoveField(
            model_name='treatedanimal',
            name='t0',
        ),
        migrations.AddField(
            model_name='treatedanimal',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registernewuser.breed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatedanimal',
            name='history',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treatedanimal',
            name='number_of_animals',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatedanimal',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatedanimal',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registernewuser.species'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t0', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T0')),
                ('pr', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PR')),
                ('rr', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='RR')),
                ('clinical_finding', models.TextField(blank=True, max_length=200, verbose_name='Clinical Finding')),
                ('differential_diag', models.TextField(blank=True, max_length=200)),
                ('rumen_motility', models.TextField(max_length=100, verbose_name='Rumen Motility')),
                ('dx', models.ManyToManyField(blank=True, to='regulartreatedanimals.Disease', verbose_name='Dx')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulartreatedanimals.treatedanimal')),
            ],
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulartreatedanimals.treatment', verbose_name='Treatment ID'),
        ),
    ]
