# Generated by Django 4.0 on 2022-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0019_remove_treatedanimal_clinical_finding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='paid',
        ),
        migrations.AddField(
            model_name='treatment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
