# Generated by Django 4.0 on 2022-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_in_out', '0010_remove_drugout_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugout',
            old_name='receiver',
            new_name='kebele',
        ),
        migrations.AddField(
            model_name='drugout',
            name='received_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
