# Generated by Django 3.1.3 on 2021-04-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registernewuser', '0007_auto_20210330_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(auto_now_add=True, verbose_name='Service Date')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registernewuser.customer', verbose_name='Case Number')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.clinicalservice', verbose_name='Service ID')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registernewuser.service', verbose_name='Service Type')),
            ],
        ),
    ]
