# Generated by Django 3.1.3 on 2021-04-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registernewuser', '0007_auto_20210330_0640'),
        ('clinicalservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovided',
            name='quantity',
        ),
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(auto_now_add=True, verbose_name='Service Date')),
                ('last_calving_date', models.DateField(verbose_name='Last Calving Date')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('ai_frequency', models.CharField(max_length=30, verbose_name='AI Frequency')),
                ('bull_number', models.PositiveBigIntegerField(verbose_name='Bull Number')),
                ('pd_result', models.CharField(max_length=50, verbose_name='PD Result')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registernewuser.customer', verbose_name='Case Number')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registernewuser.service', verbose_name='Service Type')),
            ],
        ),
    ]
