# Generated by Django 3.1.3 on 2021-04-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0003_auto_20210417_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovided',
            name='clinical_service',
        ),
        migrations.RemoveField(
            model_name='serviceprovided',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='AIService',
        ),
        migrations.DeleteModel(
            name='ClinicalService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceProvided',
        ),
    ]
