# Generated by Django 3.1.3 on 2021-04-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registernewuser', '0008_delete_service'),
        ('clinicalservices', '0004_auto_20210417_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(auto_now_add=True, verbose_name='Service Date')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registernewuser.customer', verbose_name='Case Number')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.clinicalservice', verbose_name='Service ID')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.service', verbose_name='Service Type')),
            ],
        ),
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(auto_now_add=True, verbose_name='Service Date')),
                ('last_calving_date', models.DateField(verbose_name='Last Calving Date')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('ai_frequency', models.CharField(max_length=30, verbose_name='AI Frequency')),
                ('bull_number', models.PositiveBigIntegerField(verbose_name='Bull Number')),
                ('pd_result', models.CharField(max_length=50, verbose_name='PD Result')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registernewuser.customer', verbose_name='Case Number')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.service', verbose_name='Service Type')),
            ],
        ),
    ]
