# Generated by Django 3.1.3 on 2021-04-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0005_aiservice_clinicalservice_service_serviceprovided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiservice',
            name='service_type',
        ),
    ]
