# Generated by Django 3.1.3 on 2021-04-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0006_remove_aiservice_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservice',
            name='service_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.service', verbose_name='Service Type'),
            preserve_default=False,
        ),
    ]
