# Generated by Django 3.1.3 on 2021-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0007_aiservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=6),
        ),
    ]
