# Generated by Django 3.1.3 on 2021-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0008_auto_20210624_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
