# Generated by Django 3.1.3 on 2021-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0011_clinicalservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='service',
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='service',
            field=models.ManyToManyField(to='clinicalservices.Service'),
        ),
    ]
