# Generated by Django 3.1.3 on 2021-07-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0013_delete_serviceprovided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservice',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.service', verbose_name='Service Type'),
        ),
    ]
