# Generated by Django 4.0 on 2022-06-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicalservices', '0016_clinicalservice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservice',
            name='case_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='case_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
