# Generated by Django 4.0 on 2022-06-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinicalservices', '0017_aiservice_case_holder_clinicalservice_case_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='aiservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='aiservice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aiservice',
            name='case_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
