# Generated by Django 4.0 on 2022-06-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0019_alter_aiservice_ai_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiservice',
            old_name='quantity',
            new_name='qnty',
        ),
    ]
