# Generated by Django 4.0 on 2022-08-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir_exam', '0005_alter_abattoirexam_result_alter_abattoirexam_sex'),
        ('clinicalservices', '0022_remove_clinicalservice_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiservice',
            name='price',
        ),
        migrations.AddField(
            model_name='aiservice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiservice',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinicalservices.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiservice',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abattoir_exam.color'),
        ),
    ]
