# Generated by Django 4.0 on 2022-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0023_remove_aiservice_price_aiservice_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservice',
            name='qnty',
            field=models.PositiveIntegerField(),
        ),
    ]
