# Generated by Django 4.0 on 2022-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0024_alter_aiservice_qnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservice',
            name='bull_number',
            field=models.PositiveIntegerField(),
        ),
    ]
