# Generated by Django 4.0 on 2022-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0025_alter_aiservice_bull_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
