# Generated by Django 4.0 on 2022-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0026_alter_aiservice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalservice',
            name='number_of_service',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
