# Generated by Django 4.0 on 2022-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0027_clinicalservice_number_of_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='service_type',
            field=models.ManyToManyField(to='clinicalservices.Service'),
        ),
    ]
