# Generated by Django 4.0 on 2022-10-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalservices', '0028_remove_clinicalservice_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='clinicalservice',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicalservices.service'),
        ),
    ]
