# Generated by Django 4.0 on 2022-06-27 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0010_alter_prescription_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
