# Generated by Django 4.0 on 2022-08-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0015_alter_treatedanimal_pr_alter_treatedanimal_rr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
