# Generated by Django 4.0 on 2022-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulartreatedanimals', '0020_remove_prescription_paid_treatment_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='delivered',
        ),
        migrations.AddField(
            model_name='treatment',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
