# Generated by Django 4.0 on 2022-07-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('drug_in_out', '0003_drugin_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugin',
            name='dropped_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugin',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='drugout',
            name='store_man',
            field=models.CharField(max_length=100),
        ),
    ]
