# Generated by Django 4.0 on 2022-07-12 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drug_in_out', '0004_alter_drugin_dropped_by_alter_drugin_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugin',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='drugout',
            name='date_received',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugout',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
