# Generated by Django 4.0 on 2022-07-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('drug_in_out', '0005_drugin_total_drugout_date_received_drugout_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrogOutCashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bank_slip_number', models.CharField(max_length=100)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_by', to='auth.user')),
                ('payment_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drug_in_out.drugout')),
            ],
        ),
    ]
