# Generated by Django 4.0 on 2022-07-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('drug_in_out', '0006_drogoutcashdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drogoutcashdeposit',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drug_out_confirmed_by', to='auth.user'),
        ),
    ]
