# Generated by Django 4.0 on 2022-07-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_in_out', '0008_rename_drogoutcashdeposit_drugoutcashdeposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugin',
            old_name='date_received',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='drugout',
            old_name='date_received',
            new_name='date',
        ),
    ]
