# Generated by Django 4.0 on 2023-06-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_in_out', '0011_rename_receiver_drugout_kebele_drugout_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugoutcashdeposit',
            name='payment_for',
        ),
    ]
